services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./src/backend/ruby:/app
    ports:
      - '4567:4567'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    networks:
      - mynetwork
    command: bundle exec ruby app.rb
    depends_on:
      - postgres
      - redis
      - prometheus # Ensure that Prometheus is available for Grafana and app monitoring

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - whoknows_variations_postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - mynetwork
    ports:
      - '5432:5432'

  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    co