services:
  app:
    build:
      context: .
    volumes:
      - ./src/backend/ruby:/app
    ports:
      - "4567:4567"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/whoknows_db
    command: bundle exec ruby app.rb

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
