scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187'] # Postgres exporter should be on port 9187
  - job_name: 'app'
    static_configs:
      - targets: ['app:4567'] # App is exposed on port 4567 for Prometheus metrics
