source 'https://rubygems.org'

gem 'sinatra'         # Sinatra framework
gem 'sqlite3'         # SQLite database
gem 'sequel'          # ORM for easier database interactions
gem 'rack'            # Rack is a modular Ruby web server interface
gem 'dotenv'          # For managing environment variables (optional but recommended)
gem 'json'            # For JSON handling
gem 'rackup' 
gem 'sinatra-flash'
gem 'redis'
gem 'redis-rack-cache'
gem 'httparty'
gem 'pg'       # PostgreSQL driver for Ruby
gem 'activerecord'  # ORM for database interaction
gem 'sinatra-activerecord'  # Sinatra extension for ActiveRecord
gem 'puma'
gem 'sinatra-contrib'
gem 'rack-cache'
gem 'prometheus-client'









