name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/whoknows_variations-app:${{ github.sha }} -f .devcontainer/Dockerfile .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/whoknows_variations-app:${{ github.sha }}

      - name: Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to DigitalOcean
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -T root@${{ secrets.DO_DROPLET_IP }} <<EOF
          # Ensure the app is healthy before stopping the old container
          curl -s http://localhost:80/health || exit 1
          
          # Pull the new Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/whoknows_variations-app:${{ github.sha }}
          
          # Gracefully stop the old container
          docker stop sinatra-app || true
          docker wait sinatra-app || true
          docker rm sinatra-app || true

          # Run the new container
          docker run -d --name sinatra-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/whoknows_variations-app:${{ github.sha }}
          
          # Health check again after starting the new container
          while ! curl -s http://localhost:80/health; do
              echo "Waiting for the new app to be healthy..."
              sleep 5
          done
          EOF
